# Generated by Django 4.0.5 on 2022-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photos', models.FileField(blank=True, default='APLU', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=100)),
                ('personnes', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('annee_de_sortie', models.DateField()),
                ('affiche', models.FileField(blank=True, default='APLU', null=True, upload_to='')),
                ('realisateur', models.CharField(max_length=100)),
                ('categorie', models.ManyToManyField(to='filmographie.categorie')),
            ],
        ),
    ]
